
(function(){var delta=function(diff){var r=[],charnum=0;for(var i=0;i<diff.length;i++){var d=diff[i];switch(d[0]){case-1:r.push([0,d[1].length,charnum]);break;case 0:charnum+=d[1].length;break;case 1:r.push([1,d[1],charnum]);charnum+=d[1].length;break;}}
return r;};var applydelta=function(delta,copy){var r=copy;for(var i=0;i<delta.length;i++){var d=delta[i];switch(d[0]){case 0:r=r.slice(0,d[2])+r.slice(d[2]+d[1]);break;case 1:r=r.slice(0,d[2])+d[1]+r.slice(d[2]);break;}}
return r;};var solve=function(delta,newdelta){for(var i=0;i<newdelta.length;i++){var nd=newdelta[i];for(var j=0;j<delta.length;j++){nd=newdelta[i];if(nd===undefined||delta[j]===undefined){break;}
switch(nd[0]){case 0:if(delta[j][2]>nd[2]){solveRightOfDel(delta,newdelta,[i,j]);}else{solveLeftOfDel(delta,newdelta,[i,j]);}
break;case 1:if(nd[2]<=delta[j][2]){delta[j][2]+=nd[1].length;}else{if(delta[j][0]===0){if(delta[j][1]<nd[2]-delta[j][2]){nd[2]-=delta[j][1];}else{delta[j][1]+=nd[1].length;nd[2]=delta[j][2];j++;delta.splice(j,0,nd);}}else{nd[2]+=delta[j][1].length;}}
break;}}}
return delta;};var solveRightOfDel=function(delta,newdelta,ij){var i=ij[0],j=ij[1];var nd=newdelta[i];var fromStartToEndDel=(nd[2]+nd[1])-delta[j][2];if(nd[2]+nd[1]<=delta[j][2]){delta[j][2]-=nd[1];}else{if(delta[j][0]===1){nd[1]+=delta[j][1].length;delta[j][2]=nd[2];ij[0]++;i++;newdelta.splice(i,0,delta[j]);}else{var toend=delta[j][2]+delta[j][1]-(nd[2]+nd[1]);if(toend<=0){nd[1]-=delta[j][1];delta.splice(j,1);}else{nd[1]-=fromStartToEndDel;delta[j][2]=nd[2];delta[j][1]=toend;}}}};var solveLeftOfDel=function(delta,newdelta,ij){var i=ij[0],j=ij[1];var nd=newdelta[i];var fromStartToEndDel=(nd[2]+nd[1])-delta[j][2];switch(delta[j][0]){case 0:if(delta[j][2]+delta[j][1]<=nd[2]){nd[2]-=delta[j][1];}else{var toend=nd[2]+nd[1]-(delta[j][2]+delta[j][1])
if(toend<=0){delta[j][1]-=nd[1];newdelta.splice(i,1);}else{nd[1]-=-fromStartToEndDel;nd[2]=delta[j][2];nd[1]=toend;}}
break;case 1:nd[2]+=delta[j][1].length;break;}};window.Diff={};window.Diff.delta=delta;window.Diff.applydelta=applydelta;window.Diff.solve=solve;})();