#!/bin/bash

if [ -z "$1" ]; then
  echo "Build the index file under meta/.index, for use by reverse-hash."
  echo "Usage: ./tools/meta/build-index ./web/ > ./meta/.index"
  exit 1
fi

WEB="$1"

find "$WEB"/ | (
  while read file; do
    vpath="$( echo "$file" | sed "s:^$WEB::" )"
    echo "$vpath" | xargs ./tools/meta/hash | echo "$( cat - ) $vpath"
  done
)
