#!/usr/bin/env node

var driver = require('../../lib/driver.js');

var virtualPath = process.argv[2];
if (!virtualPath) {
  console.log("Convert a virtual path to the disk hash.");
  console.log("Usage: ./tools/meta/hash /foo/bar");
  process.exit(1);
}
console.log(driver.pathHash(virtualPath));

