#!/usr/bin/env node

var driver = require('../../lib/driver.js');

var virtualPath = process.argv[2];
if (!virtualPath) {
  console.log("Convert a virtual path to the metafile (on disk)");
  console.log("Usage: ./tools/meta/path /foo/bar");
  process.exit(1);
}
console.log(driver.metafile(virtualPath));
