update:
	@git clone git://github.com/marijnh/CodeMirror2.git mirror
	@cp -rf mirror/lib .
	@cp -rf mirror/mode .
	@cp -rf mirror/theme .
	@cp -rf mirror/LICENSE .
	@cp -rf mirror/README.md .
	@rm -rf mirror
